### ISSUE TITLE
Victor Bushilo Lesson 11-1

### ISSUE THREAD

**Issue by alexander-sidorov** [alexander-sidorov/m-pt1-63-23#132]
Привет Виктор, это задание после урока 11, уровень 1.

## Контекст

- папка: `services/webapp/`
- ветка: `victor-bushilo-lesson-11-1`
- базовый URL: `/~/victor_bushilo` (`{base_url}`)
- макс. оценка: 7
- дедлайн: вторник 11.04.2023 23:00

## Описание

В целях единообразия работы с запросом и ответом, в ветке `main` появились два типа:
- `framework.http.Request` [(код)](https://github.com/alexander-sidorov/m-pt1-63-23/blob/ae76339a8fbb448bc69a613a1231b6ea23cf504e/services/webapp/framework/http.py#L21)
- `framework.http.Response` [(код)](https://github.com/alexander-sidorov/m-pt1-63-23/blob/ae76339a8fbb448bc69a613a1231b6ea23cf504e/services/webapp/framework/http.py#L28)

Изменился алгоритм, как сервер будет работать с твоим приложением (функция `main` в модуле `routing.py`).
Теперь, ей в качестве параметра будет передаваться объект типа `Request`, и ожидается, что она вернёт объект типа `Response` как результат своей работы. Поэтому, задание сводится к тому, чтобы адаптировать свой код под новые правила.

## Чеклист

- [x] в модуле `framework.routing` в функции `list_routers` раскомментирована строка с твоим именем [(код)](https://github.com/alexander-sidorov/m-pt1-63-23/blob/ae76339a8fbb448bc69a613a1231b6ea23cf504e/services/webapp/framework/routing.py#L14)
- [x] с тестов убран декоратор `@pytest.mark.xfail`
- [x] код приложения (`routing.main`) работает с `Request` и `Response`.
- [ ] тесты адаптированы под новые правила
- [ ] тесты одобряют код
- [x] линтеры одобряют код
- [x] пулл-реквест связан с этой задачей с помощью `closes #` [(как сделать)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] пулл-реквест зелёный
- [ ] ветка пулл-реквеста вмержена в `main`

## В помощь

- [DTO](https://ru.wikipedia.org/wiki/DTO)
- [Python Dataclasses](https://docs.python.org/3.10/library/dataclasses.html)
- [Pydantic](https://docs.pydantic.dev/)
- [Enumeration - Перечисляемый тип](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D0%B9_%D1%82%D0%B8%D0%BF)
- [Python enum](https://docs.python.org/3.10/library/enum.html)

**Comment by alexander-sidorov** [comment]
Виктор, а где пулл-реквест?

**Comment by VictorBushido** [comment]
#porridgeinmyhead
Решил скопировать все файлы. По твоему примеру упростить и разобраться. По итогу дебага не все пока понимаю.

**Comment by VictorBushido** [comment]
Почему тесты не одобряют твой код?

**Comment by alexander-sidorov** [comment]
Виктор, судя [по экшенам](https://github.com/alexander-sidorov/m-pt1-63-23/actions), одобряют.

По-прежнему не вижу твой пулл-реквест, чтобы он был присоединён к задаче, отсюда не могу посмотреть конкретный код и сказать, что не так.
