### ISSUE TITLE
Vadim Zhurau Lesson 13

### ISSUE THREAD

**Issue by alexander-sidorov** [alexander-sidorov/m-pt1-63-23#165]
Вадим, это домашнее задание после урока 13.

## Контекст

- макс. оценка: 10
- дедлайн: среда 19.04.2023 19:30

## Описание

Делаем полноценное АПИ чтобы работать с контактами. Данные контактов уже будут сохраняться на сервере, но могут не сохраняться между перезапусками сервера.

Примеры работы с АПИ, документацию, можно посмотреть вот тут:

- [Swagger](https://m-pt1-63-23.sidorov.dev/~/alexander_sidorov/contacts/docs) - тут и позапускать запросы можно
- [ReDoc](https://m-pt1-63-23.sidorov.dev/~/alexander_sidorov/contacts/redoc)

Описание контакта, какие у него будут поля, какие из них обязательные — оставляю на твоё усмотрение.

Где хранить контакты — оставляю на твоё усмотрение.

Если контакты будешь хранить в файле / базе данных — убедись, что файл/база не попадает в коммит.

Также убедись, что файл или база не сохраняется, или используется каждый раз новая — при работе тестов. Иначе тесты будут зависеть от предыдущих прогонов.

### 7 баллов

- [ ] можно прочитать все контакты
- [ ] можно прочитать конкретный контакт по его ИД
- [ ] можно создать новый контакт и затем увидеть его в списке всех контактов, и получить его по ИД
- [ ] можно обновить данные контакта и затем увидеть новые значения в списке всех контактов, и получить их по ИД
- [ ] можно удалить контакт по его ИД и затем убедиться, что контакт не показывается в списке всех контактов, а также его нельзя получить по его ИД
- [ ] каждый элементарный функционал (напр. _"чтение всех контактов"_) реализован в отдельной функции/классе
- [ ] функционал сохранения/создания/получения данных из хранилища реализован в отдельных функциях (`contact_list.append(c)` — не ок, `save_contact(c)` — ок)
- [ ] работоспособность всего функционала подтверждается тестом (тестами)
- [ ] линтеры одобряют код
- [ ] пулл-реквест связан с этой задачей с помощью `closes #` [(как сделать)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] пулл-реквест зелёный
- [ ] ветка пулл-реквеста вмержена в `main`

### 9 баллов

- [ ] данные хранятся в файле или базе данных
- [ ] база данных очищается или пересоздаётся для каждого запуска тестов
- [ ] база данных не попала в пулл-реквест

### 10 баллов

- [ ] апи реализовано с использованием FastAPI с сохранением функционала всего остального всех остальных, что уже реализовано и работает на сервере

## В помощь

- [API](https://en.wikipedia.org/wiki/API)
- [REST](https://habr.com/ru/articles/483202/)
- [HTTP Methods](https://developer.mozilla.org/ru/docs/Web/HTTP/Methods)
- [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)
- [HTTP status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
- [SQLite](https://docs.python.org/3/library/sqlite3.html)
- [FastAPI](https://fastapi.tiangolo.com/)

**Comment by VadimZhurav** [comment]
![Image](https://user-images.githubusercontent.com/118134370/233465256-6373fc48-bc8a-465e-bdf1-39367e1ba215.png)

Перестал работать код, выдаёт вот такую инфу, когда делаю вот такой запрос: http://localhost:8000/~/vadim_zhurau/contacts/1

**Comment by alexander-sidorov** [comment]
score: 0 (deadline, no pull request)
