### ISSUE TITLE
Nikita Harbatsevich Lesson 03 Level 1

### ISSUE THREAD

**Issue by alexander-sidorov** [alexander-sidorov/m-pt1-63-23#26]
Идея: перенести существующую логику из asgi.py в свой пакет

Контекст:

- папка `services/webapp/`
- ветка `nikita-harbatsevich-lesson-03`

Задание сделано, если:

- [x] в папке `hw/` есть папка с твоим именем и фамилией в такой форме: `nikita_harbatsevich`
- [x] в папке ^ есть пустой файл `__init__.py`
- [x] в папке ^ есть файл `lesson03.py`. Это будет модуль урока.
- [x] в модуле урока ^ есть функция `view`, которая принимает один параметр: `path`, и возвращает строку при её вызове
- [x] кодом, внутри функции, написан алгоритм: если в качестве аргумента функции передали строку `"/~/nikita_harbatsevich"`, то функция возвращает строку `"Hello from Nikita Harbatsevich"`
- [x] когда сервер работает, по ссылке [http://localhost:8000/~/nikita_harbatsevich](http://localhost:8000/~/nikita_harbatsevich) в браузере появляется текст `Hello from Nikita Harbatsevich`
- [x] код закомичен и запушен в ветку из контекста
- [x] пулл-реквест создан
- [x] название пулл-реквеста - `Nikita Harbatsevich Lesson 03`
- [ ] пулл-реквест вмержен

**Comment by NikitaHarbatsevich** [comment]
Nikita Harbatsevich Lesson 03

**Comment by alexander-sidorov** [comment]
Никита, в `Ready` переводит Гитхаб, когда ПР можно мержить.

Если хочешь, чтобы твой ПР посмотрели - переводи в `Blocker`
