### ISSUE TITLE
Vadim Zhurau Lesson 03 Level 1

### ISSUE THREAD

**Issue by alexander-sidorov** [alexander-sidorov/m-pt1-63-23#29]
Идея: перенести существующую логику из asgi.py в свой пакет

Контекст:

- папка `services/webapp/`
- ветка `vadim-zhurav-lesson-03`

Задание сделано, если:

- [x] в папке `hw/` есть папка с твоим именем и фамилией в такой форме: `vadim_zhurav`
- [x] в папке ^ есть пустой файл `__init__.py`
- [x] в папке ^ есть файл `lesson03.py`. Это будет модуль урока.
- [x] в модуле урока ^ есть функция `view`, которая принимает один параметр: `path`, и возвращает строку при её вызове
- [x] кодом, внутри функции, написан алгоритм: если в качестве аргумента функции передали строку `"/~/vadim_zhurav"`, то функция возвращает строку `"Hello from Vadim Zhurav"`
- [x] когда сервер работает, по ссылке [http://localhost:8000/~/vadim_zhurav](http://localhost:8000/~/vadim_zhurav) в браузере появляется текст `Hello from Vadim Zhurav`
- [x] код закомичен и запушен в ветку из контекста
- [x] пулл-реквест создан
- [x] название пулл-реквеста - `Vadim Zhurav Lesson 03`
- [ ] пулл-реквест вмержен

**Comment by VadimZhurav** [comment]
Только сервер будет работать по ссылке http://localhost:8000/~/vadim_zhurau/ , а не http://localhost:8000/~/vadim_zhurav , так как моя фамилия на английском правильно пишется "Zhurau".
